#!/bin/bash

# Fix SSH auth socket location so agent forwarding works with tmux
# This also requires a setting in `tmux.conf`
if [ ! -S ~/.ssh/ssh_auth_sock ] && [ -S "$SSH_AUTH_SOCK" ]; then
  ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
