################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
# > hyprctl monitors all

env = GDK_SCALE,1.75

# device, resolution[@refresh], resolution, scale
monitor=DP-2,highres,-1440x-450,1,transform,1 # left monitor, rotated 90 deg
monitor=DP-1,highres,0x0,1.25 # left monitor, horizontal
