################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
# > hyprctl monitors all

env = GDK_SCALE,1.75

# device, resolution[@refresh], resolution, scale
monitor=DP-1,highres,0x0,1.25 # left monitor, horizontal
monitor=DP-2,highres,3072x-450,1,transform,3 # right monitor, rotated 270 deg
