[[conn]]
name = "slipstream (local)"
type = "postgres"
user = "postgres"
password = "postgres"
host = "localhost"
port = 5432
database = "app"

[[conn]]
name = "wallet (local)"
type = "mysql"
user = "root"
password = "root"
host = "localhost"
port = 59006
database = "db"

[[conn]]
name = "wof (local)"
type = "mysql"
user = "root"
password = "root"
host = "localhost"
port = 59007
database = "db"

