import = ["~/.config/alacritty/themes/everforest_dark.toml"]

[window]
padding = { x = 0, y = 0 }

[font]
size = 7
offset = { x = 0, y = 3 }

normal = { family = "monospace", style = "Regular" }
bold = { family = "monospace", style = "Medium" }
italic = { family = "monospace", style = "Medium Italic" }
